---
- hosts: 'local'
  connection: local
  vars:
    brew_packages:
      - tree
      - ghq
      - peco
      - fzf
      - jq
      - zsh
      - zsh-completions
      - mise
      - starship
      - font-hack-nerd-font
      - orbstack
  tasks:
    - name: Update Homebrew
      homebrew:
        update_homebrew: yes
    - name: Install Homebrew Packages
      homebrew:
        name: "{{ item }}"
        state: "present"
      with_items: "{{ brew_packages }}"
