---
- hosts: 'local'
  connection: local
  vars:
    brew_packages:
      - git
      - ghq
      - peco
      - fzf
      - tree
      - jq
      - zsh
      - zsh-completions
      - tmux
      - nodenv
      - yarn
    pip3_packages:
      - powerline-shell
  tasks:
    - name: Update Homebrew
      homebrew:
        update_homebrew: yes
    - name: Install Homebrew Packages
      homebrew:
        name: "{{ item }}"
        state: "present"
      with_items: "{{ brew_packages }}"
    - name: Update Pip3
      become: true
      become_method: sudo
      become_flags: -H
      pip:
        name: pip
        executable: pip3
        state: latest
    - name: Install Pip3 Packages
      become: true
      become_method: sudo
      become_flags: -H
      pip:
        name: "{{ pip3_packages }}"
        executable: pip3
        state: present
