---
- hosts: 'local'
  connection: local
  vars:
    brew_taps:
      - garethr/kubeval
      - argoproj/tap
    brew_packages:
      - cask
      - git
      - tree
      - jq
      - ghq
      - peco
      - fzf
      - zsh
      - zsh-completions
      - tmux
      - libev # Locustで使うために入れている
      - cfssl
      - neovim
      - goenv
      - pyenv
      - nodenv
      - circleci
      - awscli
      - tfenv # TODO: hashicorp/tap/terraform に切り替えるかどうするか悩み中
      - docker
      - docker-clean
      - kubectl
      - kubectx
      - kube-ps1
      - kubeval
      - txn2/tap/kubefwd
      - kind
      - helm
      - helmfile
      - stern
      - weaveworks/tap/eksctl
      - datawire/blackbird/telepresence
      - istioctl
      - fluxctl
      - argoproj/tap/argocd
      - aylei/tap/kubectl-debug
      - derailed/popeye/popeye
    brew_cask_packages:
      - osxfuse # TODO dependencies datawire/blackbird/telepresence 
      - divvy
      - google-japanese-ime
      - dropbox
      - kindle
      - deepl
      - 1password
      - gas-mask
      - discord
      - karabiner-elements
      - docker
#      - line
      - google-chrome
      - firefox
      - slack
      - microsoft-teams
      - zoom
      - spotify
      - spotmenu
      - notion
      - microsoft-remote-desktop
      - intellij-idea
      - goland
    pip3_packages:
      - botocore==1.15.17
      - locustio==0.13.5
      - aws-mfa
      - powerline-shell
    npm_packages:
      - awsp
  tasks:
    # https://docs.ansible.com/ansible/2.7/modules/homebrew_tap_module.html
    - name: Add homebrew tap repositories
      homebrew_tap:
        name: "{{ item }}"
        state: "present"
      with_items: "{{ brew_taps }}"

    # https://docs.ansible.com/ansible/2.7/modules/homebrew_cask_module.html
    - name: Install Homebrew Cask Packages
      homebrew_cask:
        name: "{{ item }}"
        state: "present"
        install_options: "appdir=/Applications"
        accept_external_apps: yes
      with_items: "{{ brew_cask_packages }}"

    # https://docs.ansible.com/ansible/2.7/modules/homebrew_module.html
    - name: Update Homebrew
      homebrew:
        update_homebrew: yes

    - name: Install Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: "present"

    - name: Update Pip3
      become: true
      become_method: sudo
      become_flags: -H
      pip:
        name: pip
        executable: pip3
        state: latest
    - name: Install Pip3 Packages
      become: true
      become_method: sudo
      become_flags: -H
      pip:
        name: "{{ pip3_packages }}"
        executable: pip3
        state: present
#    - name: Install npm Packages
#      become: true
#      become_method: sudo
#      npm:
#        name: "{{ npm_packages }}"
#        global: yes
#        state: latest
#        notwork...!!! # executable: "{{ ansible_env.HOME }}/.nodenv/shims/npm"
#      environment:
#        PATH: "{{ ansible_env.HOME }}/.nodenv/shims:{{ ansible_env.PATH }}"
